file_format: "1"
id: StagErgo
name: StagErgo
type: shield
url: https://keeb.io/products/StagErgo-keyboard-split-ergonomic-keyboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - StagErgo_left
  - StagErgo_right
